### ISSUE TITLE
How to get spanMap as an array after span is finished?

### ISSUE THREAD

**Issue by emildd** [Vinelab/tracing-laravel#25]
how to get the Spanmap result as an array like the attached screenshot?

example debug `dd($span);` after `$span->finish();` 

<img width="377" alt="Screen Shot 2020-10-08 at 09 26 16" src="https://user-images.githubusercontent.com/3082522/95407847-5d260480-0948-11eb-92ea-2af8fbd2d1ec.png">

**Comment by adiachenko** [comment]
I think this question is better asked at [zipkin-php](https://github.com/openzipkin/zipkin-php) since I'm not even sure if this information is exposed by underlying instrumentation. As mentioned in the [issue you've previously opened](https://github.com/Vinelab/tracing-laravel/issues/24) we don't have direct access to flushed spans.

**Comment by emildd** [comment]
Thankyou @adiachenko

**Comment by jcchavezs** [comment]
@emildd feel free to open an issue in zipkin-php explaining your use case.
