### ISSUE TITLE
Too few arguments to function 'Illuminate\Support\Manager::createDriver()'

### ISSUE THREAD

**Issue by KinaneD** [Vinelab/tracing-laravel#29]
Running on:
- Laravel 8.15
- PHP v7.4
- Phpunit v9.4.3

In previous Laravel installations 5.8.*, to silence tracing while running phpunit tests we adapt our `phpunit.xml` as such:
```xml
    <php>
       ...
        <env name="TRACING_DRIVER" value="null"/>
    </php>
```

Doing this same in this installation result with the following error:
```shell
ArgumentCountError: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /code/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 105 and exactly 1 expected
/code/vendor/laravel/framework/src/Illuminate/Support/Manager.php:94
/code/vendor/laravel/framework/src/Illuminate/Support/Manager.php:105
/code/vendor/laravel/framework/src/Illuminate/Support/Manager.php:80
/code/vendor/vinelab/tracing-laravel/src/TracingServiceProvider.php:75
/code/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
/code/vendor/laravel/framework/src/Illuminate/Container/Container.php:691
/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:796
/code/vendor/laravel/framework/src/Illuminate/Container/Container.php:637
/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:781
/code/vendor/laravel/framework/src/Illuminate/Container/Container.php:1280
/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:198
/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:166
/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:255
/code/vendor/vinelab/tracing-laravel/src/Integration/Concerns/TracesLucidArchitecture.php:67
/code/vendor/vinelab/tracing-laravel/src/Integration/Concerns/TracesLucidArchitecture.php:55
/code/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:391
/code/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:236
/code/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:432
```

We were able to work around this by adding a single quote for the `null` driver:
`<server name="TRACING_DRIVER" value="'null'"/>`

Is this an exepcted behaviour?

**Comment by adiachenko** [comment]
I just tried installed the lib on the project with the following dependencies:

- Laravel 8.12 (then bumped to 8.16 just in case)
- PHP 7.4
- PHPUnit 9.4.2 (then bumped to 9.4.3 just in case)

Then I ran some random HTTP test and ensured it triggered tracing. Next, I added the following line to my phpunit.xml and triggered the test again:

```
<env name="TRACING_DRIVER" value="null"/>
```

Trace was not dispatched this time around and the error did not occur. Could there be something else that messes up environment variables on the project?

I tried to dd driver value in TracingDriverManager:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10194667/100487910-b83bd280-3113-11eb-9d34-f8033648a969.png">

I get null here (as in actual null, not a string null). Then the next line ensures that the string "null" is returned as a name of the driver. Please check your TracingDriverManager relative to the project whether it works the same way. Also just to be sure check if you don't somehow override TracingDriverManager::class binding it in the project's service provider. 

You shouldn't need to quote the value and there is definitely something weird going on here.

**Comment by IlliaBalia** [comment]
@KinaneD @adiachenko 
I get an empty string when I `dd($this->config->get('tracing.driver')`

Regardless of this, it is okay to use `'null'`, since this is the default driver. 
An alternative solution is to use `empty($this->config->get('tracing.driver'))` instead of `is_null($this->config->get('tracing.driver'))`

**Comment by adiachenko** [comment]
@IlliaBalia This seems to indicate some project specific issue with how config values are resolved. Under normal circumstances you can't get empty string here unless you explicitly specified empty string.

The check itself is pretty standard, see [how official Laravel packages handle null driver for example](https://github.com/laravel/scout/blob/8.x/src/EngineManager.php#L108). The only observed difference from the linked example is that config repository is accessed via an earlier saved reference rather than global helper functional, but that shouldn't affect the logic anyhow (if you aren't sure, you can try replacing `$this->config->get` with `config`).

Need help replicating this on a pristine Laravel project.

**Comment by IlliaBalia** [comment]
@adiachenko indeed, we `trim()` end values. Apparently, this causes `null` to become an empty string.

**Comment by adiachenko** [comment]
@IlliaBalia Ah, I see, I seem to recall this is done due to issues with Kubernetes secrets. 

Then I suggest you simply replace the following line in your projects:

```php
'driver' => trim(env('TRACING_DRIVER', 'zipkin')),
```

with

```php
'driver' => trim(env('TRACING_DRIVER', 'zipkin') ?? 'null'),
```

and for the rest follow this package documentation like you normally would to avoid confusion.
