### ISSUE TITLE
Has anyone considered adding more events to Laravel?

### ISSUE THREAD

**Issue by JeroenVanOort** [Vinelab/tracing-laravel#33]
I would be great if Laravel had more events that we could use to start and finish spans. Like QueryStarted in addition to [QueryExecuted](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Events/QueryExecuted.php), CacheQueryStarted in addition to [CacheHit](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/Events/CacheHit.php) and [CacheMissed](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/Events/CacheMissed.php), etc. Maybe even some new events for the HTTP client.

Do you know if anyone has tried this already? I'm willing to work on it, but if someone has already tried and got their PR rejected, I may want to save myself the effort.

**Comment by KinaneD** [comment]
Hi @JeroenVanOort 
I am not aware of any attempts to do so.
On the long run one concern i can think of is an overwhelming tracing span, where too much details are accounted for, perhaps jeopardising visibility and storage too?
I see no reason to not trace whatever event one can be interested in, which leads me towards thinking of a need to cherrypick/define such events of interest per project.

**Comment by adiachenko** [comment]
@JeroenVanOort @KinaneD 

I entertained similar ideas in the past, but the suggested approach it's problematic for a number of reasons:

- according to the [spec](https://opentracing.io/docs/overview/spans/), spans are supposed to represent individual unit of work done in a distributed system. Think of it as a microservice call that can take a form of http request, console command call or scheduled job. Breaking it down (as spans) any further than that isn't practical from the perspective of developer who inspects the behavior of the complex system. In my anecdotal experience, the resulting trace is too unwieldy for the applications this was designed for.
- you don't want to log too much data due to bandwith and storage concerns. We don't currently support these drivers, but some instrumentation works through UDP protocol with maximum span size of 64kb. Storage would be an even bigger issue as you're supposed to log data on each request.
- lastly, if we did implement something like that, the smart way to do that would be using **logs** inside spans. However, [as we pointed out in documentation for this package](https://github.com/Vinelab/tracing-laravel#jaeger), contextualized logging (see example pic below) is only available in Jaeger and we can't easily offer this feature without Jaeger instrumentation for PHP. There are some unofficial options but they kinda suck. We currently use Jaeger via Zipkin compat mode.
![image](https://user-images.githubusercontent.com/10194667/135837490-eef3d2d3-03d3-4f2a-bc0f-6fa37df75476.png)

**Comment by jcchavezs** [comment]
I am late to the party but I promise I had this issue in my list to loop-in for days.

First of all I like the idea of using framework specific events in the span. For example in Symfony we do something like that for controller resolution: https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/KernelListener.php#L147. This is not a minor thing because it helps to understand how much time the request spends resolving the controller and how much time in the actual logic of the controller. Similar for the rest of events, that is why `annotations`/`logs` were meant to (*meaningful events in the span lifecycle*). Unless specific cases I would say framework events are really something the user wants to look at in many cases so maybe we don't add it by default but allow to enable it.

As for what @adiachenko points out I honestly disagree with the arguments and I think there are some misunderstandings there:

> according to the spec, spans are supposed to represent individual unit of work done in a distributed system. Think of it as a microservice call that can take a form of http request, console command call or scheduled job, etc. Breaking it down (as spans) any further than that isn't practical from the perspective of developer who inspects the behavior of the complex system. In my anecdotal experience, the resulting trace would be too unwieldy for the applications this was designed for.

Yes, creating other spans is overkill, unless you are a proxy (tho this is questionable, [see this thread](https://github.com/Kong/kong-plugin-zipkin/issues/89)) 

> you don't want to log too much data due to bandwith and storage concerns. We don't currently support these drivers, but some instrumentation works through UDP protocol with maximum span size of 64kb. Storage would be an even bigger issue as you're supposed to log data on each request.

I feel this is harmful. First of all, specific protocols should be driving these kind of decisions, Jaeger is the only tool that I know that uses UDP for traces and I don't even think they are too happy with UDP either, in terms of amount of data, trend is people moving towards HTTP, GRPC or async messaging for reporting and more so, adding way more data that one might expect ([see this spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes)). I would say due to storage costs it is fair to keep this feature as opt-in tho (depending on the amount of events, remember tracing data is mostly ephemeral)

> lastly, if we did implement something like that, the smart way to do that would be using logs inside spans. However, as we pointed out in documentation for this package, contextualized logging (see example pic below) is only available in Jaeger and we can't easily offer this feature without Jaeger instrumentation for PHP. There are some unofficial options but they kinda suck. We currently use Jaeger via Zipkin compat mode.

This one is unrelated, I don't think introducing logging is desired here (that is a completely different business) but more about logs/annotations which both Zipkin and Jaeger (like other clones of Zipkin) support.

**Comment by adiachenko** [comment]
@jcchavezs Can you please comment on how you would approach implementing something akin to breadcrumbs for SQL queries? Not the detection of event itself, but it would look like in Zipkin.

As far as I'm aware, Zipkin instrumentation only has spans, tags inside spans (key:value pairs) and annotations (arbitrary string values with an implicit timestamp at their creation). Jaeger logs are different because each one can hold its own collection of key:value pairs. That's what I meant in the above comment by saying they're more suitable for this kind of events that require a bit more details.

It seems that we agree(?) that spans are overkill for this purpose. I would also argue that tags aren't suitable as well because semantically they apply to the whole span and also used for search/filtering.

Which kinda leaves us with time annotations where all of the relevant info about the event must be displayed in a single formatted string. This is indeed something that every driver support. But would it be convenient to create and read such annotations for generic framework events when you can't format them easily? Considering related storage costs and added complexity to this package it just makes me feel a bit meh about the idea. 

After all, we wouldn't want to introduce a feature we don't personally use. Note that I don't necessarily dismiss the suggestion. I'd be glad to reopen the discussion on tracing generic Laravel events if we have something more concrete like a PR. I am just saying we don't intend to actively pursue this idea ourselves at the moment because we weren't fully satisfied with what we came up with.

**Comment by adiachenko** [comment]
@jcchavezs I'd be glad to reopen the discussion if we have something like a PR or examples to illustrate specific Laravel events that you'd like to annotate and the proposed implementation.

This discussion opened with examples like database queries and cache hits that may require a whole bunch of additional metadata to make a sense of (sql statement, bindings, execution time, etc.). This is why I singled out Jaeger previously because its log message structure (which is a collection of key:value pairs) feels suited for this use case assuming you can eat storage costs.

From what I understand you don't suggest to use spans for this as well, but rather simple time annotations which is something supported by Zipkin as well. But I am not sure I understood what you suggest to annotate exactly considering the earlier mentioned examples (what would be the contents of the string associated with timestamp exactly). Or maybe if you have own use case in mind, it would be better to see sample annotations that are relevant to Laravel.
